services:
    - type: web
      name: ml-event-tagger
      runtime: docker
      region: oregon
      plan: free
      branch: main
      dockerfilePath: ./Dockerfile
      dockerContext: .
      envVars:
          - key: PORT
            value: 8000
          - key: PYTHONUNBUFFERED
            value: 1
      healthCheckPath: /health
      autoDeploy: true
